In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
df=pd.read_csv('/content/drive/MyDrive/MiniProject/retail_price.csv')

Mounted at /content/drive

In [ ]:
print(df.columns)

Index(['product_id', 'product_category_name', 'month_year', 'qty',
       'total_price', 'freight_price', 'unit_price', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_score', 'customers', 'weekday', 'weekend', 'holiday', 'month',
       'year', 's', 'volume', 'comp_1', 'ps1', 'fp1', 'comp_2', 'ps2', 'fp2',
       'comp_3', 'ps3', 'fp3', 'lag_price'],
      dtype='object')

In [ ]:
df.head()

,product_id,product_category_name,month_year,qty,total_price,freight_price,unit_price,product_name_lenght,product_description_lenght,product_photos_qty,...,comp_1,ps1,fp1,comp_2,ps2,fp2,comp_3,ps3,fp3,lag_price
0,bed1,bed_bath_table,01-05-2017,1,45.95,15.100000,45.95,39,161,2,...,89.9,3.9,15.011897,215.000000,4.4,8.760000,45.95,4.0,15.100000,45.90
1,bed1,bed_bath_table,01-06-2017,3,137.85,12.933333,45.95,39,161,2,...,89.9,3.9,14.769216,209.000000,4.4,21.322000,45.95,4.0,12.933333,45.95
2,bed1,bed_bath_table,01-07-2017,6,275.70,14.840000,45.95,39,161,2,...,89.9,3.9,13.993833,205.000000,4.4,22.195932,45.95,4.0,14.840000,45.95
3,bed1,bed_bath_table,01-08-2017,4,183.80,14.287500,45.95,39,161,2,...,89.9,3.9,14.656757,199.509804,4.4,19.412885,45.95,4.0,14.287500,45.95
4,bed1,bed_bath_table,01-09-2017,2,91.90,15.100000,45.95,39,161,2,...,89.9,3.9,18.776522,163.398710,4.4,24.324687,45.95,4.0,15.100000,45.95

In [ ]:
df.tail()

,product_id,product_category_name,month_year,qty,total_price,freight_price,unit_price,product_name_lenght,product_description_lenght,product_photos_qty,...,comp_1,ps1,fp1,comp_2,ps2,fp2,comp_3,ps3,fp3,lag_price
671,bed5,bed_bath_table,01-05-2017,1,215.00,8.760000,215.000000,56,162,5,...,89.9,3.9,15.011897,215.000000,4.4,8.760000,45.95,4.0,15.100000,214.950000
672,bed5,bed_bath_table,01-06-2017,10,2090.00,21.322000,209.000000,56,162,5,...,89.9,3.9,14.769216,209.000000,4.4,21.322000,45.95,4.0,12.933333,215.000000
673,bed5,bed_bath_table,01-07-2017,59,12095.00,22.195932,205.000000,56,162,5,...,89.9,3.9,13.993833,205.000000,4.4,22.195932,45.95,4.0,14.840000,209.000000
674,bed5,bed_bath_table,01-08-2017,52,10375.00,19.412885,199.509804,56,162,5,...,89.9,3.9,14.656757,199.509804,4.4,19.412885,45.95,4.0,14.287500,205.000000
675,bed5,bed_bath_table,01-09-2017,32,5222.36,24.324687,163.398710,56,162,5,...,89.9,3.9,18.776522,163.398710,4.4,24.324687,45.95,4.0,15.100000,199.509804

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 676 entries, 0 to 675
Data columns (total 30 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  676 non-null    object
 1   product_category_name       676 non-null    object
 2   month_year                  676 non-null    object
 3   qty                         676 non-null    int64
 4   total_price                 676 non-null    float64
 5   freight_price               676 non-null    float64
 6   unit_price                  676 non-null    float64
 7   product_name_lenght         676 non-null    int64
 8   product_description_lenght  676 non-null    int64
 9   product_photos_qty          676 non-null    int64
 10  product_weight_g            676 non-null    int64
 11  product_score               676 non-null    float64
 12  customers                   676 non-null    int64
 13  weekday                     676 non-null    int64
 14  weekend                     676 non-null    int64
 15  holiday                     676 non-null    int64
 16  month                       676 non-null    int64
 17  year                        676 non-null    int64
 18  s                           676 non-null    float64
 19  volume                      676 non-null    int64
 20  comp_1                      676 non-null    float64
 21  ps1                         676 non-null    float64
 22  fp1                         676 non-null    float64
 23  comp_2                      676 non-null    float64
 24  ps2                         676 non-null    float64
 25  fp2                         676 non-null    float64
 26  comp_3                      676 non-null    float64
 27  ps3                         676 non-null    float64
 28  fp3                         676 non-null    float64
 29  lag_price                   676 non-null    float64
dtypes: float64(15), int64(12), object(3)
memory usage: 158.6+ KB

In [ ]:
df.describe()

,qty,total_price,freight_price,unit_price,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_score,customers,...,comp_1,ps1,fp1,comp_2,ps2,fp2,comp_3,ps3,fp3,lag_price
count,676.000000,676.000000,676.000000,676.000000,676.000000,676.000000,676.000000,676.000000,676.000000,676.000000,...,676.000000,676.000000,676.000000,676.000000,676.000000,676.000000,676.000000,676.000000,676.000000,676.000000
mean,14.495562,1422.708728,20.682270,106.496800,48.720414,767.399408,1.994083,1847.498521,4.085503,81.028107,...,79.452054,4.159467,18.597610,92.930079,4.123521,18.620644,84.182642,4.002071,17.965007,107.399684
std,15.443421,1700.123100,10.081817,76.182972,9.420715,655.205015,1.420473,2274.808483,0.232021,62.055560,...,47.933358,0.121652,9.406537,49.481269,0.207189,6.424174,47.745789,0.233292,5.533256,76.974657
min,1.000000,19.900000,0.000000,19.900000,29.000000,100.000000,1.000000,100.000000,3.300000,1.000000,...,19.900000,3.700000,0.095439,19.900000,3.300000,4.410000,19.900000,3.500000,7.670000,19.850000
25%,4.000000,333.700000,14.761912,53.900000,40.000000,339.000000,1.000000,348.000000,3.900000,34.000000,...,49.910000,4.100000,13.826429,53.900000,4.100000,14.485000,53.785714,3.900000,15.042727,55.668750
50%,10.000000,807.890000,17.518472,89.900000,51.000000,501.000000,1.500000,950.000000,4.100000,62.000000,...,69.900000,4.200000,16.618984,89.990000,4.200000,16.811765,59.900000,4.000000,16.517110,89.900000
75%,18.000000,1887.322500,22.713558,129.990000,57.000000,903.000000,2.000000,1850.000000,4.200000,116.000000,...,104.256549,4.200000,19.732500,117.888889,4.200000,21.665238,99.990000,4.100000,19.447778,129.990000
max,122.000000,12095.000000,79.760000,364.000000,60.000000,3006.000000,8.000000,9750.000000,4.500000,339.000000,...,349.900000,4.500000,57.230000,349.900000,4.400000,57.230000,255.610000,4.400000,57.230000,364.000000

In [ ]:
df.isnull()

,product_id,product_category_name,month_year,qty,total_price,freight_price,unit_price,product_name_lenght,product_description_lenght,product_photos_qty,...,comp_1,ps1,fp1,comp_2,ps2,fp2,comp_3,ps3,fp3,lag_price
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
671,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
672,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
673,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
674,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
675,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
df.isnull().sum()

product_id                    0
product_category_name         0
month_year                    0
qty                           0
total_price                   0
freight_price                 0
unit_price                    0
product_name_lenght           0
product_description_lenght    0
product_photos_qty            0
product_weight_g              0
product_score                 0
customers                     0
weekday                       0
weekend                       0
holiday                       0
month                         0
year                          0
s                             0
volume                        0
comp_1                        0
ps1                           0
fp1                           0
comp_2                        0
ps2                           0
fp2                           0
comp_3                        0
ps3                           0
fp3                           0
lag_price                     0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
df['product_id']=encoder.fit_transform(df['product_id'])
df

,product_id,product_category_name,month_year,qty,total_price,freight_price,unit_price,product_name_lenght,product_description_lenght,product_photos_qty,...,comp_1,ps1,fp1,comp_2,ps2,fp2,comp_3,ps3,fp3,lag_price
0,0,bed_bath_table,01-05-2017,1,45.95,15.100000,45.950000,39,161,2,...,89.9,3.9,15.011897,215.000000,4.4,8.760000,45.95,4.0,15.100000,45.900000
1,0,bed_bath_table,01-06-2017,3,137.85,12.933333,45.950000,39,161,2,...,89.9,3.9,14.769216,209.000000,4.4,21.322000,45.95,4.0,12.933333,45.950000
2,0,bed_bath_table,01-07-2017,6,275.70,14.840000,45.950000,39,161,2,...,89.9,3.9,13.993833,205.000000,4.4,22.195932,45.95,4.0,14.840000,45.950000
3,0,bed_bath_table,01-08-2017,4,183.80,14.287500,45.950000,39,161,2,...,89.9,3.9,14.656757,199.509804,4.4,19.412885,45.95,4.0,14.287500,45.950000
4,0,bed_bath_table,01-09-2017,2,91.90,15.100000,45.950000,39,161,2,...,89.9,3.9,18.776522,163.398710,4.4,24.324687,45.95,4.0,15.100000,45.950000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
671,4,bed_bath_table,01-05-2017,1,215.00,8.760000,215.000000,56,162,5,...,89.9,3.9,15.011897,215.000000,4.4,8.760000,45.95,4.0,15.100000,214.950000
672,4,bed_bath_table,01-06-2017,10,2090.00,21.322000,209.000000,56,162,5,...,89.9,3.9,14.769216,209.000000,4.4,21.322000,45.95,4.0,12.933333,215.000000
673,4,bed_bath_table,01-07-2017,59,12095.00,22.195932,205.000000,56,162,5,...,89.9,3.9,13.993833,205.000000,4.4,22.195932,45.95,4.0,14.840000,209.000000
674,4,bed_bath_table,01-08-2017,52,10375.00,19.412885,199.509804,56,162,5,...,89.9,3.9,14.656757,199.509804,4.4,19.412885,45.95,4.0,14.287500,205.000000
675,4,bed_bath_table,01-09-2017,32,5222.36,24.324687,163.398710,56,162,5,...,89.9,3.9,18.776522,163.398710,4.4,24.324687,45.95,4.0,15.100000,199.509804

In [ ]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
df['product_category_name']=encoder.fit_transform(df['product_category_name'])
df

,product_id,product_category_name,month_year,qty,total_price,freight_price,unit_price,product_name_lenght,product_description_lenght,product_photos_qty,...,comp_1,ps1,fp1,comp_2,ps2,fp2,comp_3,ps3,fp3,lag_price
0,0,0,01-05-2017,1,45.95,15.100000,45.950000,39,161,2,...,89.9,3.9,15.011897,215.000000,4.4,8.760000,45.95,4.0,15.100000,45.900000
1,0,0,01-06-2017,3,137.85,12.933333,45.950000,39,161,2,...,89.9,3.9,14.769216,209.000000,4.4,21.322000,45.95,4.0,12.933333,45.950000
2,0,0,01-07-2017,6,275.70,14.840000,45.950000,39,161,2,...,89.9,3.9,13.993833,205.000000,4.4,22.195932,45.95,4.0,14.840000,45.950000
3,0,0,01-08-2017,4,183.80,14.287500,45.950000,39,161,2,...,89.9,3.9,14.656757,199.509804,4.4,19.412885,45.95,4.0,14.287500,45.950000
4,0,0,01-09-2017,2,91.90,15.100000,45.950000,39,161,2,...,89.9,3.9,18.776522,163.398710,4.4,24.324687,45.95,4.0,15.100000,45.950000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
671,4,0,01-05-2017,1,215.00,8.760000,215.000000,56,162,5,...,89.9,3.9,15.011897,215.000000,4.4,8.760000,45.95,4.0,15.100000,214.950000
672,4,0,01-06-2017,10,2090.00,21.322000,209.000000,56,162,5,...,89.9,3.9,14.769216,209.000000,4.4,21.322000,45.95,4.0,12.933333,215.000000
673,4,0,01-07-2017,59,12095.00,22.195932,205.000000,56,162,5,...,89.9,3.9,13.993833,205.000000,4.4,22.195932,45.95,4.0,14.840000,209.000000
674,4,0,01-08-2017,52,10375.00,19.412885,199.509804,56,162,5,...,89.9,3.9,14.656757,199.509804,4.4,19.412885,45.95,4.0,14.287500,205.000000
675,4,0,01-09-2017,32,5222.36,24.324687,163.398710,56,162,5,...,89.9,3.9,18.776522,163.398710,4.4,24.324687,45.95,4.0,15.100000,199.509804

In [ ]:
df.drop('product_description_lenght', axis=1, inplace=True, errors='ignore')
df

,product_id,product_category_name,month_year,qty,total_price,freight_price,unit_price,product_name_lenght,product_photos_qty,product_weight_g,...,comp_1,ps1,fp1,comp_2,ps2,fp2,comp_3,ps3,fp3,lag_price
0,0,0,01-05-2017,1,45.95,15.100000,45.950000,39,2,350,...,89.9,3.9,15.011897,215.000000,4.4,8.760000,45.95,4.0,15.100000,45.900000
1,0,0,01-06-2017,3,137.85,12.933333,45.950000,39,2,350,...,89.9,3.9,14.769216,209.000000,4.4,21.322000,45.95,4.0,12.933333,45.950000
2,0,0,01-07-2017,6,275.70,14.840000,45.950000,39,2,350,...,89.9,3.9,13.993833,205.000000,4.4,22.195932,45.95,4.0,14.840000,45.950000
3,0,0,01-08-2017,4,183.80,14.287500,45.950000,39,2,350,...,89.9,3.9,14.656757,199.509804,4.4,19.412885,45.95,4.0,14.287500,45.950000
4,0,0,01-09-2017,2,91.90,15.100000,45.950000,39,2,350,...,89.9,3.9,18.776522,163.398710,4.4,24.324687,45.95,4.0,15.100000,45.950000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
671,4,0,01-05-2017,1,215.00,8.760000,215.000000,56,5,9750,...,89.9,3.9,15.011897,215.000000,4.4,8.760000,45.95,4.0,15.100000,214.950000
672,4,0,01-06-2017,10,2090.00,21.322000,209.000000,56,5,9750,...,89.9,3.9,14.769216,209.000000,4.4,21.322000,45.95,4.0,12.933333,215.000000
673,4,0,01-07-2017,59,12095.00,22.195932,205.000000,56,5,9750,...,89.9,3.9,13.993833,205.000000,4.4,22.195932,45.95,4.0,14.840000,209.000000
674,4,0,01-08-2017,52,10375.00,19.412885,199.509804,56,5,9750,...,89.9,3.9,14.656757,199.509804,4.4,19.412885,45.95,4.0,14.287500,205.000000
675,4,0,01-09-2017,32,5222.36,24.324687,163.398710,56,5,9750,...,89.9,3.9,18.776522,163.398710,4.4,24.324687,45.95,4.0,15.100000,199.509804

In [ ]:
df.drop('product_name_lenght', axis=1, inplace=True, errors='ignore')
df

,product_id,product_category_name,month_year,qty,total_price,freight_price,unit_price,product_photos_qty,product_weight_g,product_score,...,comp_1,ps1,fp1,comp_2,ps2,fp2,comp_3,ps3,fp3,lag_price
0,0,0,01-05-2017,1,45.95,15.100000,45.950000,2,350,4.0,...,89.9,3.9,15.011897,215.000000,4.4,8.760000,45.95,4.0,15.100000,45.900000
1,0,0,01-06-2017,3,137.85,12.933333,45.950000,2,350,4.0,...,89.9,3.9,14.769216,209.000000,4.4,21.322000,45.95,4.0,12.933333,45.950000
2,0,0,01-07-2017,6,275.70,14.840000,45.950000,2,350,4.0,...,89.9,3.9,13.993833,205.000000,4.4,22.195932,45.95,4.0,14.840000,45.950000
3,0,0,01-08-2017,4,183.80,14.287500,45.950000,2,350,4.0,...,89.9,3.9,14.656757,199.509804,4.4,19.412885,45.95,4.0,14.287500,45.950000
4,0,0,01-09-2017,2,91.90,15.100000,45.950000,2,350,4.0,...,89.9,3.9,18.776522,163.398710,4.4,24.324687,45.95,4.0,15.100000,45.950000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
671,4,0,01-05-2017,1,215.00,8.760000,215.000000,5,9750,4.4,...,89.9,3.9,15.011897,215.000000,4.4,8.760000,45.95,4.0,15.100000,214.950000
672,4,0,01-06-2017,10,2090.00,21.322000,209.000000,5,9750,4.4,...,89.9,3.9,14.769216,209.000000,4.4,21.322000,45.95,4.0,12.933333,215.000000
673,4,0,01-07-2017,59,12095.00,22.195932,205.000000,5,9750,4.4,...,89.9,3.9,13.993833,205.000000,4.4,22.195932,45.95,4.0,14.840000,209.000000
674,4,0,01-08-2017,52,10375.00,19.412885,199.509804,5,9750,4.4,...,89.9,3.9,14.656757,199.509804,4.4,19.412885,45.95,4.0,14.287500,205.000000
675,4,0,01-09-2017,32,5222.36,24.324687,163.398710,5,9750,4.4,...,89.9,3.9,18.776522,163.398710,4.4,24.324687,45.95,4.0,15.100000,199.509804

In [ ]:
df.drop(columns=['ps3'], inplace=True, errors='ignore')
df

,product_id,product_category_name,month_year,qty,total_price,freight_price,unit_price,product_photos_qty,product_weight_g,product_score,...,volume,comp_1,ps1,fp1,comp_2,ps2,fp2,comp_3,fp3,lag_price
0,0,0,01-05-2017,1,45.95,15.100000,45.950000,2,350,4.0,...,3800,89.9,3.9,15.011897,215.000000,4.4,8.760000,45.95,15.100000,45.900000
1,0,0,01-06-2017,3,137.85,12.933333,45.950000,2,350,4.0,...,3800,89.9,3.9,14.769216,209.000000,4.4,21.322000,45.95,12.933333,45.950000
2,0,0,01-07-2017,6,275.70,14.840000,45.950000,2,350,4.0,...,3800,89.9,3.9,13.993833,205.000000,4.4,22.195932,45.95,14.840000,45.950000
3,0,0,01-08-2017,4,183.80,14.287500,45.950000,2,350,4.0,...,3800,89.9,3.9,14.656757,199.509804,4.4,19.412885,45.95,14.287500,45.950000
4,0,0,01-09-2017,2,91.90,15.100000,45.950000,2,350,4.0,...,3800,89.9,3.9,18.776522,163.398710,4.4,24.324687,45.95,15.100000,45.950000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
671,4,0,01-05-2017,1,215.00,8.760000,215.000000,5,9750,4.4,...,12600,89.9,3.9,15.011897,215.000000,4.4,8.760000,45.95,15.100000,214.950000
672,4,0,01-06-2017,10,2090.00,21.322000,209.000000,5,9750,4.4,...,12600,89.9,3.9,14.769216,209.000000,4.4,21.322000,45.95,12.933333,215.000000
673,4,0,01-07-2017,59,12095.00,22.195932,205.000000,5,9750,4.4,...,12600,89.9,3.9,13.993833,205.000000,4.4,22.195932,45.95,14.840000,209.000000
674,4,0,01-08-2017,52,10375.00,19.412885,199.509804,5,9750,4.4,...,12600,89.9,3.9,14.656757,199.509804,4.4,19.412885,45.95,14.287500,205.000000
675,4,0,01-09-2017,32,5222.36,24.324687,163.398710,5,9750,4.4,...,12600,89.9,3.9,18.776522,163.398710,4.4,24.324687,45.95,15.100000,199.509804

In [ ]:
df.drop(columns=['fp2'], inplace=True)
df

,product_id,product_category_name,month_year,qty,total_price,freight_price,unit_price,product_photos_qty,product_weight_g,product_score,...,s,volume,comp_1,ps1,fp1,comp_2,ps2,comp_3,fp3,lag_price
0,0,0,01-05-2017,1,45.95,15.100000,45.950000,2,350,4.0,...,10.267394,3800,89.9,3.9,15.011897,215.000000,4.4,45.95,15.100000,45.900000
1,0,0,01-06-2017,3,137.85,12.933333,45.950000,2,350,4.0,...,6.503115,3800,89.9,3.9,14.769216,209.000000,4.4,45.95,12.933333,45.950000
2,0,0,01-07-2017,6,275.70,14.840000,45.950000,2,350,4.0,...,12.071651,3800,89.9,3.9,13.993833,205.000000,4.4,45.95,14.840000,45.950000
3,0,0,01-08-2017,4,183.80,14.287500,45.950000,2,350,4.0,...,9.293873,3800,89.9,3.9,14.656757,199.509804,4.4,45.95,14.287500,45.950000
4,0,0,01-09-2017,2,91.90,15.100000,45.950000,2,350,4.0,...,5.555556,3800,89.9,3.9,18.776522,163.398710,4.4,45.95,15.100000,45.950000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
671,4,0,01-05-2017,1,215.00,8.760000,215.000000,5,9750,4.4,...,0.649351,12600,89.9,3.9,15.011897,215.000000,4.4,45.95,15.100000,214.950000
672,4,0,01-06-2017,10,2090.00,21.322000,209.000000,5,9750,4.4,...,6.493506,12600,89.9,3.9,14.769216,209.000000,4.4,45.95,12.933333,215.000000
673,4,0,01-07-2017,59,12095.00,22.195932,205.000000,5,9750,4.4,...,38.311688,12600,89.9,3.9,13.993833,205.000000,4.4,45.95,14.840000,209.000000
674,4,0,01-08-2017,52,10375.00,19.412885,199.509804,5,9750,4.4,...,33.766234,12600,89.9,3.9,14.656757,199.509804,4.4,45.95,14.287500,205.000000
675,4,0,01-09-2017,32,5222.36,24.324687,163.398710,5,9750,4.4,...,20.779221,12600,89.9,3.9,18.776522,163.398710,4.4,45.95,15.100000,199.509804

In [ ]:
df.drop(columns=['fp3'], inplace=True)
df

,product_id,product_category_name,month_year,qty,total_price,freight_price,unit_price,product_photos_qty,product_weight_g,product_score,...,year,s,volume,comp_1,ps1,fp1,comp_2,ps2,comp_3,lag_price
0,0,0,01-05-2017,1,45.95,15.100000,45.950000,2,350,4.0,...,2017,10.267394,3800,89.9,3.9,15.011897,215.000000,4.4,45.95,45.900000
1,0,0,01-06-2017,3,137.85,12.933333,45.950000,2,350,4.0,...,2017,6.503115,3800,89.9,3.9,14.769216,209.000000,4.4,45.95,45.950000
2,0,0,01-07-2017,6,275.70,14.840000,45.950000,2,350,4.0,...,2017,12.071651,3800,89.9,3.9,13.993833,205.000000,4.4,45.95,45.950000
3,0,0,01-08-2017,4,183.80,14.287500,45.950000,2,350,4.0,...,2017,9.293873,3800,89.9,3.9,14.656757,199.509804,4.4,45.95,45.950000
4,0,0,01-09-2017,2,91.90,15.100000,45.950000,2,350,4.0,...,2017,5.555556,3800,89.9,3.9,18.776522,163.398710,4.4,45.95,45.950000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
671,4,0,01-05-2017,1,215.00,8.760000,215.000000,5,9750,4.4,...,2017,0.649351,12600,89.9,3.9,15.011897,215.000000,4.4,45.95,214.950000
672,4,0,01-06-2017,10,2090.00,21.322000,209.000000,5,9750,4.4,...,2017,6.493506,12600,89.9,3.9,14.769216,209.000000,4.4,45.95,215.000000
673,4,0,01-07-2017,59,12095.00,22.195932,205.000000,5,9750,4.4,...,2017,38.311688,12600,89.9,3.9,13.993833,205.000000,4.4,45.95,209.000000
674,4,0,01-08-2017,52,10375.00,19.412885,199.509804,5,9750,4.4,...,2017,33.766234,12600,89.9,3.9,14.656757,199.509804,4.4,45.95,205.000000
675,4,0,01-09-2017,32,5222.36,24.324687,163.398710,5,9750,4.4,...,2017,20.779221,12600,89.9,3.9,18.776522,163.398710,4.4,45.95,199.509804

In [ ]:
df.drop(columns=['month_year'], inplace=True)
df

,product_id,product_category_name,qty,total_price,freight_price,unit_price,product_photos_qty,product_weight_g,product_score,customers,...,year,s,volume,comp_1,ps1,fp1,comp_2,ps2,comp_3,lag_price
0,0,0,1,45.95,15.100000,45.950000,2,350,4.0,57,...,2017,10.267394,3800,89.9,3.9,15.011897,215.000000,4.4,45.95,45.900000
1,0,0,3,137.85,12.933333,45.950000,2,350,4.0,61,...,2017,6.503115,3800,89.9,3.9,14.769216,209.000000,4.4,45.95,45.950000
2,0,0,6,275.70,14.840000,45.950000,2,350,4.0,123,...,2017,12.071651,3800,89.9,3.9,13.993833,205.000000,4.4,45.95,45.950000
3,0,0,4,183.80,14.287500,45.950000,2,350,4.0,90,...,2017,9.293873,3800,89.9,3.9,14.656757,199.509804,4.4,45.95,45.950000
4,0,0,2,91.90,15.100000,45.950000,2,350,4.0,54,...,2017,5.555556,3800,89.9,3.9,18.776522,163.398710,4.4,45.95,45.950000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
671,4,0,1,215.00,8.760000,215.000000,5,9750,4.4,57,...,2017,0.649351,12600,89.9,3.9,15.011897,215.000000,4.4,45.95,214.950000
672,4,0,10,2090.00,21.322000,209.000000,5,9750,4.4,61,...,2017,6.493506,12600,89.9,3.9,14.769216,209.000000,4.4,45.95,215.000000
673,4,0,59,12095.00,22.195932,205.000000,5,9750,4.4,123,...,2017,38.311688,12600,89.9,3.9,13.993833,205.000000,4.4,45.95,209.000000
674,4,0,52,10375.00,19.412885,199.509804,5,9750,4.4,90,...,2017,33.766234,12600,89.9,3.9,14.656757,199.509804,4.4,45.95,205.000000
675,4,0,32,5222.36,24.324687,163.398710,5,9750,4.4,54,...,2017,20.779221,12600,89.9,3.9,18.776522,163.398710,4.4,45.95,199.509804

In [ ]:
x = df[
    [
        "product_id",
        "product_category_name",
        "qty",
        "freight_price",
        "product_photos_qty",
        "lag_price"
    ]
]

y = df["unit_price"]

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42
)
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)
print("Training Data Size:", len(x_train))
print("Testing Data Size:", len(x_test))

Training Data Size: 540
Testing Data Size: 136

In [ ]:
selected_features=df[["product_id","product_category_name","qty","freight_price","product_photos_qty","lag_price"]]
selected_features

,product_id,product_category_name,qty,freight_price,product_photos_qty,lag_price
0,0,0,1,15.100000,2,45.900000
1,0,0,3,12.933333,2,45.950000
2,0,0,6,14.840000,2,45.950000
3,0,0,4,14.287500,2,45.950000
4,0,0,2,15.100000,2,45.950000
...,...,...,...,...,...,...
671,4,0,1,8.760000,5,214.950000
672,4,0,10,21.322000,5,215.000000
673,4,0,59,22.195932,5,209.000000
674,4,0,52,19.412885,5,205.000000
675,4,0,32,24.324687,5,199.509804

In [ ]:
from sklearn.linear_model import LinearRegression
linearRegression=LinearRegression()
linearRegression.fit(x_train,y_train)
print("model trained successfully")

model trained successfully

In [ ]:
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    root_mean_squared_error,
    r2_score
)

In [ ]:
y_train_pred = linearRegression.predict(x_train)
train_comparison = pd.DataFrame({'Actual_Train': y_train.values.ravel(), 'Predicted_Train': y_train_pred})
display(train_comparison.head(10))

   Actual_Train  Predicted_Train
0    149.000000       140.791645
1     97.588235        82.519556
2     98.323333       102.129203
3     58.990000        58.793833
4     79.800000        80.057091
5     19.990000        18.671416
6    117.975000       116.950394
7     86.900000        85.434891
8    101.000000       102.741533
9    105.642857       106.871235

In [ ]:
y_pred=linearRegression.predict(x_test)
comparison=pd.DataFrame({'Actual':y_test.values.ravel(),'Predicted':y_pred})
comparison.head(10)

       Actual   Predicted
0  174.433333  230.729630
1  129.990000  129.661214
2   99.900000  100.875650
3   77.821429   76.890931
4   99.990000  101.277961
5   52.900000   54.336612
6  151.878437  179.709486
7   53.379104   53.430894
8   45.900000   43.182092
9  105.000000  105.140401

In [ ]:
from sklearn.metrics import mean_squared_error
mse=mean_squared_error(y_test,y_pred)
print(mse)

64.36204766259831

In [ ]:
from sklearn.metrics import mean_absolute_error
mae=mean_absolute_error(y_test,y_pred)
print(mae)

3.925347692844622

In [ ]:
from sklearn import metrics
print('R2_score',metrics.r2_score(y_test,y_pred))

R2_score 0.9880861635855709

In [ ]:
import pickle
filename="retail_linear_regression.pkl"
outfile=open(filename,"wb")
pickle.dump(linearRegression,outfile)
outfile.close()

In [ ]:
X = df[[
    "product_id",
    "product_category_name",
    "qty",
    "freight_price",
    "product_photos_qty",
    "lag_price"
]]

y = df["unit_price"]

In [ ]:
from sklearn import metrics
print('R2_score',metrics.r2_score(y_test,y_pred))

R2_score 0.9880861635855709

In [ ]:
from sklearn.ensemble import RandomForestRegressor

# Re-initialize and re-train the RandomForestRegressor model
model = RandomForestRegressor(
    n_estimators=300,
    random_state=42
)
model.fit(x_train, y_train)

print(model)

sample = [[1, 1, 10, 50, 3, 100]]

# Scale the sample using the previously fitted scaler
scaled_sample = scaler.transform(sample)

print(model.predict(scaled_sample))

RandomForestRegressor(n_estimators=300, random_state=42)
[103.25288151]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [ ]:
print(model)

sample = [[1, 1, 10, 50, 3, 100]]

print(model.predict(sample))

RandomForestRegressor(n_estimators=300, random_state=42)
[339.52388888]

In [ ]:
from sklearn import metrics
print('R2_score',metrics.r2_score(y_test,y_pred))

R2_score 0.9880861635855709

In [ ]:
import pickle

pickle.dump(scaler, open("scaler.pkl", "wb"))
pickle.dump(linearRegression, open("retail_linear_regression.pkl", "wb"))